# Use a config system to easily add/remove staff without having
# to restart BungeeCord every time new staff are added/removed
staff:
- _Ghost_
- ArtistChibi
- Bashea
- benstevens99
- Blackberryz
- CDParadis83
- Clawer47
- CringeMcKid
- DilligafGamer
- DragoniusArc
- doms101
- Esszy
- finder17
- Kevinthedude2000
- KnGhz_
- LaggyAuPlayer
- MeemsaMagician
- mrbearblue
- QueenTerra
- Redned
- RoboGolem
- Silver_Aaron
- Shadowright
- Shaur
